### ISSUE TITLE
Is there a bug in class BR?

### ISSUE THREAD

**Issue by hbk16** [SConsul/Global_Convolutional_Network#1]
`    def forward(self,x):`
`#         x_res = self.bn(x)`
`#         x_res = self.relu(x_res)`
`        x_res = self.conv1(x_res)`
`#         x_res = self.bn(x_res)`
`        x_res = self.relu(x_res)`
`        x_res = self.conv2(x_res)`
`        `
`        x = x + x_res`
`        return x`
In the method forward of class BR, the x_res is not declared before reference.

**Comment by SConsul** [comment]
You're right. I'll fix this. 
Also, the build_model.py is the most recent version of the model.
