### ISSUE TITLE
how to get the file 'cp.pth'

### ISSUE THREAD

**Issue by 296245482** [SConsul/Global_Convolutional_Network#3]
hi,
when i run the 'train_model.py', some file named 'cp.pth' is needed at line 74, how to get that file? By the way, if i comment this line, i got another error as below:

Traceback (most recent call last):
  File "train_model.py", line 139, in <module>
    train()
  File "train_model.py", line 105, in train
    outputs = net(images)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/long/Downloads//Global_Convolutional_Network-master/build_model.py", line 97, in forward
    gc_fm1 = self.br1(self.gcn1(fm1))
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/long/Downloads//Global_Convolutional_Network-master/build_model.py", line 18, in forward
    x_l = self.conv_l1(x)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
TypeError: 'float' object cannot be interpreted as an integer

didn't figure it out, thank you for your help

**Comment by SConsul** [comment]
the cp.pth is just the weights of a previously trained model. Currently, the code saves the weights of all the epochs and I can choose to continue training from the last epoch.
If you want to train a fresh model, comment this out. 
You seem to be having a type casting error, are your images of type uint8?

**Comment by 296245482** [comment]
thanks, but the images i used was the Montgomery data set, same as yours, in png format. maybe different python version? mine is 3.5.2, sorry for my ignorance

**Comment by SConsul** [comment]
Python 3.5 and 3.5.2 differences would not cause this issue. I have fixed a small error that would only arise if your machine does not have CUDA. Let me know if this solves it.

**Comment by 296245482** [comment]
still the same problem, still working on it....

**Comment by 296245482** [comment]
finally solved, the last error traceback is 

"File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/conv.py", line 301, in forward
self.padding, self.dilation, self.groups)
TypeError: 'float' object cannot be interpreted as an integer"

the float value here mentioned is 'self.padding', in 'build_model.py' line 12-15, caste the '(k[0]-1)/2' to int can solve my problem

**Comment by SConsul** [comment]
I'll incorporate the same. Thanks for bringing it up!

**Comment by SConsul** [comment]
Nice job! Word of caution: ensure your kernels of odd dimensions, else
after deconvolution, the size of the mask would not match the input image
size.
